In [11]:
import numpy as np

A = np.random.randn(4,3)
print(A)

B = np.sum(A, axis = 1, keepdims = True)

[[-0.96533326 -0.38356848 -1.71135705]
 [-0.14377654  0.62829186 -1.04948747]
 [-0.50012904 -0.23485063  0.32993067]
 [ 0.05466548  2.24364014  0.23539729]]


In [7]:
print(B.shape)

(4, 1)
