In [6]:
import numpy as np

# Broadcasting example
A = np.array([[56.0,0.0 ,1.2, 1.8], 
             [1.2, 104.0, 52.0, 8.0],
            [1.8, 135.0, 99.0, 0.9] ])

print(A)

[[ 56.    0.    1.2   1.8]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [7]:
cal = A.sum(axis=0)
print(cal)

[ 59.  239.  152.2  10.7]


In [10]:
percentage = 100 * A/cal.reshape(1,4)
print(percentage)

[[94.91525424  0.          0.78843627 16.82242991]
 [ 2.03389831 43.51464435 34.16557162 74.76635514]
 [ 3.05084746 56.48535565 65.04599212  8.41121495]]


In [19]:
# Example and General Principle

print("Array L Traspose + 100")
M = np.array([1,2,3])
print(X.T + 100)

print("Array L + 100")
L = np.array([1,2,3])
print(L + 100)

# Matrix 3x2 + Matrix 2x3 = 3x3
X1 = np.array([[1,1], [1,0], [0,1]])
X2 = np.array([[1,1,0], [1,0,0]])

print("Matrix 3x2 + 2x3 = 3x3")
print(np.dot(X1,X2))
# Matrix 2x3 + Matrix 3x2 = 2x2
X1 = np.array([[1,1,1], [1,0,1]])
X2 = np.array([[1,1], [1,0], [1,1]])

print("Matrix 2x3 + 3x2 = 2x2")
print(np.dot(X1,X2))

Array L Traspose + 100
[[101]
 [102]
 [103]]
Array L + 100
[101 102 103]
Matrix 3x2 + 2x3 = 3x3
[[2 1 0]
 [1 1 0]
 [1 0 0]]
Matrix 2x3 + 3x2 = 2x2
[[3 2]
 [2 2]]
