In [23]:
import numpy as np

In [24]:
img = np.random.randn(32,32, 3)
print(img.shape)

(32, 32, 3)


In [62]:
x = img.reshape((32*32*3,1))

#x = img.reshape((32*32,3))

#x = img.reshape((3,32*32))

#x = img.reshape((1,32*32,*3))

print(x.shape)

(3072, 1)


In [26]:
a = np.random.randn(2, 3) # a.shape = (2, 3)
b = np.random.randn(2, 1) # b.shape = (2, 1)
c = a + b
print(c.shape)

(2, 3)


In [66]:
a1 = np.random.randn(4, 3) # a.shape = (4, 3)
b1 = np.random.randn(3, 2) # b.shape = (3, 2)
c1 = np.dot(a1,b1)
print(c1.shape)

(4, 2)


In [27]:
a2 = np.random.randn(12288, 150) # a.shape = (12288, 150)
b2 = np.random.randn(150, 45) # b.shape = (150, 45)
c2 = np.dot(a2,b2)
print(c2.shape)

(12288, 45)


In [53]:
a3 = np.random.randn(3,4)
b3 = np.random.randn(4,1)
c3 = np.zeros((3,1))
    
# How do you vectorized this?
print(a3)
print(a3.shape)
print(b3.T)
print(b3.shape)

c3 = a3 + b3.T
print(c3)

[[ 0.37644264 -0.19867407 -1.64708793  1.68232701]
 [ 0.24413248 -0.95212495  0.51450329  0.05609586]
 [ 1.35094712 -0.72620129 -1.64380741 -1.06196276]]
(3, 4)
[[-0.61740569  0.1195938  -1.64534127  2.04496711]]
(4, 1)
[[-0.24096305 -0.07908027 -3.2924292   3.72729412]
 [-0.37327321 -0.83253115 -1.13083798  2.10106297]
 [ 0.73354143 -0.60660748 -3.28914868  0.98300434]]


In [54]:
a4 = np.random.randn(3, 3)
b4 = np.random.randn(3, 1)
c4 = np.dot(a4,b4)
print(c4.shape)

(3, 1)


In [ ]:
J = (a*b) + (a*c) - (b+c)