In [6]:
import numpy as np

# Python - numpy vectors
# This form is not ituitive
a = np.random.randn(5)
print(a)
print(a.shape)
# For this for example the traspose for (5,)
print(a.T)
# For this for example the dot product of a and a.T
print(np.dot(a,a.T))

[-0.06086799  0.85136668 -0.86701761 -0.05366049  0.55852938]
(5,)
[-0.06086799  0.85136668 -0.86701761 -0.05366049  0.55852938]
1.7950841802761044


In [7]:
# Is more simple
print(np.dot(a,a.T))

1.7950841802761044


In [8]:
# Whenever this is the better form
a = np.random.randn(5,1)
print(a)
print(a.shape)
# Is more intuitive
print(a.T)

[[ 0.36236979]
 [-1.01447892]
 [-0.92342011]
 [ 1.14115616]
 [-0.84333972]]
(5, 1)
[[ 0.36236979 -1.01447892 -0.92342011  1.14115616 -0.84333972]]


In [9]:
# Is more simple
print(np.dot(a,a.T))

[[ 0.13131187 -0.36761652 -0.33461955  0.41352052 -0.30560084]
 [-0.36761652  1.02916748  0.93679024 -1.15767887  0.85555037]
 [-0.33461955  0.93679024  0.85270471 -1.05376655  0.77875686]
 [ 0.41352052 -1.15767887 -1.05376655  1.30223737 -0.96238231]
 [-0.30560084  0.85555037  0.77875686 -0.96238231  0.71122188]]
